### ISSUE TITLE
无法播放mkv视频

### ISSUE THREAD

**Issue by fatewx** [circleapps/sourceplayer#1]
播放mkv视频时绿屏

**Comment by circleapps** [comment]
非常抱歉，今天才注意到这个问题。我会尽早修复。

请问您的软硬件环境是怎样的？（包括操作系统的版本号，硬件的型号和生产年份，显卡的型号）

**Comment by fatewx** [comment]
系统是macos mojave 10.14 机子是macbook pro2017 13寸  显卡 Intel Iris Plus Graphics 650 1536 MB

所有mkv都不能播放

**Comment by circleapps** [comment]
我有个用户他的软硬件和您几乎一样(他的显卡是 Intel Iris Plus Graphics 640），但是能够正常地播放所有类型的视频。

你能否试一下 https://sample-videos.com/video123/mkv/720/big_buck_bunny_720p_1mb.mkv 
这是个1M的mkv文件，这个用户是可以正常播放的，谢谢了。

我现在怀疑是我用的视频模块不支持您的这个显卡的硬件加速，所以我会在下个版本加个开关，用来关闭和开启硬件加速，保证最大的兼容性。

**Comment by circleapps** [comment]
我昨天晚上找到一个mkv文件，能够重现这个问题（显示绿屏）。经过调试后已经修复，所以您的问题，很可能也修复了。
我大概1到2周之内会把新版本上传，届时您就可以试试这个问题了。
如果您还不放心，可以把您出问题的视频的下载地址给我发一份，谢谢支持。

**Comment by fatewx** [comment]
那个视频可以播放 没有问题

**Comment by circleapps** [comment]
谢谢，下个版本验证了这个问题后，我就把这个bug关闭了。

**Comment by circleapps** [comment]
Fixed in 1.1.3
