### ISSUE TITLE
Hardware Acceleration

### ISSUE THREAD

**Issue by vsellen** [circleapps/sourceplayer#2]
Hello,
This is a very clever application. How were you able to get video acceleration to work with electron? I have been trying to get the mpv.js plugin to play accelerated video but the mpv instance pops out of the electron window.
-Vince

**Comment by circleapps** [comment]
Hello Vince,

Which OS are you working on?  My application is targeting on macOS.

I was under the impression that mpv use vo=gpu by default, so I just keep it as it is, and don't change the vo to other value.

If what you said it is true, then I need change the description of my project.  I don't want to put this misleading information for my users.

By the way, how did you get the default vo value from mpv.js?  I just tried listen to "vo" property, but got no result.

Thanks.

Edward

**Comment by vsellen** [comment]
Hello Edward,

Thanks for your quick reply. I am targeting Linux - Ubuntu in particular. I haven't had a chance to download your program on a mac yet but I look forward to it. 

Mpv does use gpu by default but if you look at the code in the plugin mpv.js https://github.com/Kagami/mpv.js/blob/c0bfcf2b11536b54326620bcdd38848e9bf14485/index.cc#L312 you'll see that it sets ```"vo" to "opengl-cb" ```. I modified a copy of that code to remove that line and hardware acceleration did work, but then the mpv instance is no longer embedded on the page.

This whole area (electron, mpv and ppapi) is pretty new to me so I can't say for sure whether your app is using the gpu or not. Perhaps you could play a demanding video in mpv itself and then in your application and compare cpu usage. My project is meant to be used on low end devices playing high quality video across three screens and so it's fairly obvious when it's just the CPU doing the work. :-) The CPU goes to 100% and the video stutters. I'll let you know if I end up finding out more - in case it is helpful to you.

Thanks again.
Vince

**Comment by circleapps** [comment]
Thanks Vince, for lettings me know it. Without your help,  it is hard to imagine when I will find my player is not gpu accelerated.

Looking forward to know what you will find. Really appreciate your help.

Edward.

**Comment by vsellen** [comment]
Closing this. I'll let you know what I find. 
Thanks.
Vince
